CREATE TABLE User_Aula50 (
  id VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
ALTER TABLE
  User_Aula50
ADD
  role ENUM("NORMAL", "ADMIN") DEFAULT("NORMAL");

DESCRIBE Users_Adress52;

CREATE TABLE Users_Adress52 (
    id VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    number VARCHAR(255) NOT NULL,
    complement VARCHAR(255),
    neighborhood VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User_Aula50(id)
  );